Numpy help you to working woth arrays efficiently, with fuctions for working in domain of linear algebra, matrics

In [1]:
import numpy as np

In [10]:
# Create an array
arr1D = np.array([1,2,3,4,5,6])
arr2D = np.array([[1,2,3], 
                  [4,5,6]])
arr3D = np.array([[[1,2,3], 
                   [4,5,6]], 
                      [[1,2,3], 
                       [4,5,6]]])

In [11]:
# Check dimension
arr3D.ndim

3

In [12]:
# Array indexing
arr1D[1]
arr2D[1,2]

np.int64(6)

In [13]:
# Array sliceing
arr2D[0:2, 0:2]
'''
varNameOfArray[dim1-startIndex:endIndex:step, dim2,..., dimN]
'''

'\nvarNameOfArray[dim1-startIndex:endIndex:step, dim2,..., dimN]\n'

In [14]:
# Data type
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''
# Check type of an arra
arr1D.dtype
strArr = np.array([1, 2, 3, 4], dtype='S')
intArr = strArr.astype('i')

In [18]:
# Copy vs View

# Copy : not affected to the origina array
copy_arr = arr1D.copy()

arr1D[0] = 42
print(arr1D)
print(copy_arr)

# View : 
view_arr = arr1D.view()

arr1D[0] = 42
print(arr1D)
print(view_arr)

# Check it is copy or view
print(arr2D.reshape(3, 2).base)

[42  2  3  4  5  6]
[42  2  3  4  5  6]
[42  2  3  4  5  6]
[42  2  3  4  5  6]
[[1 2 3]
 [4 5 6]]


In [20]:
# Shape & Reshape

print(arr1D.shape)
print(arr1D)

# Reshape
print(arr1D.reshape(3,2).shape)
print(arr1D.reshape(3,2))

# Unknow dimesion, use -1
print(arr1D.reshape(3,-1))

# Reshape is view not copy
# Use .base to check the original data, arr1D is still 1D array
print(arr1D.reshape(3,2).base)

(6,)
[42  2  3  4  5  6]
(3, 2)
[[42  2]
 [ 3  4]
 [ 5  6]]
[[42  2]
 [ 3  4]
 [ 5  6]]
[42  2  3  4  5  6]


In [21]:
# Iterating Arrays

for x in arr1D:
    print(x)

# Multidimensional Arrays
for x in arr2D:
    print(x)

for x in arr2D:
    for y in x:
        print(y)

42
2
3
4
5
6
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [24]:
# Join

arr1D_2 = np.array([6,3,9])

concat_arr = np.concat((arr1D, arr1D_2)) # Must have same dimension

In [25]:
# Split

print(np.array_split(arr1D, 3)) # Split to 3 parts

[array([42,  2]), array([3, 4]), array([5, 6])]
